apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: test-chatbot-secret-100
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/tpetkos/test-chatbot-secret-100:bd86bfd2cbb93c5180089f3d94ff3dd545bb1ef3@sha256:b66646f47f5bca3099c28be029e0a2f9e9bdd23ee7e3a387ce90f6215399d390 # use pre-built to bootstrap 
          name: app-inference
